coffee/web/views/menu.py
from flask import Blueprint, render_template, redirect, url_for, Response, send_file
from flask_login import login_required

import datetime

from coffee.web import models, forms, acl

module = Blueprint("menus", __name__, url_prefix="/menus")


@module.route("/")
@login_required
def index():
    menus = models.Menu.objects()
    return render_template(
        "menus/index.html",
        menus=menus,
    )


@module.route("/<document_id>/picture/<filename>")
@login_required
def get_image(document_id, filename):
    response = Response()
    response.status_code = 404

    menu = models.Menu.objects(id=document_id).first()
    response = menu.get_picture()
    # if note.document:
    #     response = send_file(
    #         note.document,
    #         download_name=note.document.filename,
    #         mimetype=note.document.content_type,
    #     )
    return response

@module.route("detail/<menu_id>", methods=["GET", "POST"])
@login_required
def read(menu_id):
    menu = models.Menu.objects.get(id=menu_id)
    form = forms.coffee.MenuForm(obj=menu)
    return render_template(
        "detail/index.html",
        form=form,
        menu=menu,
    )

coffee/web/templates/menus/index.html
{% extends "base/default-page.html" %}

{% block content %}
<div class="ui stackable grid" style="justify-content: center;">
    <div class="nine wide column">
        <div class="ui segment">
            <div class="ui three column stackable grid">
                {% for menu in menus | sort(attribute='updated_date', reverse=True) %}
                <div class="column">
                    <div class="ui special cards">
                        <div class="brown card">
                            <div class="blurring dimmable image">
                                <div class="ui dimmer">
                                    <div class="content">
                                        <div class="center">
                                            <a class="ui inverted button"
                                                href="{{ url_for('menus.read', menu_id=menu.id) }}">Read more</a>
                                        </div>
                                    </div>
                                </div>
                                <img class="ui fluid image"
                                    src="{{ url_for('menus.get_image', document_id=menu.id, filename=menu.document.filename) }}"
                                    style="height: 17em;" />
                            </div>
                            <div class="extra content">
                                <span class="right floated">
                                    <i class="clock outline icon"></i>
                                    {{ menu.updated_date.strftime("%H:%M:%S") }}
                                </span>
                                <span class="left floated">
                                    <i class="calendar alternate outline icon"></i>
                                    {{ menu.updated_date.strftime("%d-%h-%Y") }}
                                </span>
                            </div>

                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="four wide column">
        <div class="ui segment">
            <p style="font-size: 18px; font-weight: bold; margin-bottom: 10px;">Locate coffee places around</p>
            <div class="mapouter">
                <div class="gmap_canvas">
                    <iframe width="100%" height="500" id="gmap_canvas"
                        src="https://maps.google.com/maps?q=hatyai%20coffee&t=&z=13&ie=UTF8&iwloc=&output=embed"
                        frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
                    <a href="https://123movies-to.org"></a><br>
                </div>
                <div style="margin-top: 20%;">
                    <iframe width="100%" height="430" allow="microphone;"
                        src="https://console.dialogflow.com/api-client/demo/embedded/84739b6c-83e4-498a-aef7-fc0ef493f11f"></iframe>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

{% block additional_js %}
<script>
    $('.special.cards .image').dimmer({
        // As hover is not working on mobile, you might use click on those devices as fallback
        on: 'ontouchstart' in document.documentElement ? 'click' : 'hover'
    });
</script>
{% endblock %}